### ISSUE TITLE
Use `ceviche-challenges` for inverse design examples

### ISSUE THREAD

**Issue by ianwilliamson** [flaport/inverse_design#15]
Very cool to see this repository!

I see that the inverse design examples in the documentation are using the much older [inverse design workshop code](https://github.com/fancompute/workshop-invdesign) that I created when I was back at Stanford. Just as an FYI, along with the [Inverse Design of Photonic Devices with Strict Foundry Fabrication Constraints](https://doi.org/10.1021/acsphotonics.2c00313) paper, we did release a codebase that enables one to easily setup and call all of the design challenges we present in the paper. It's really easy to just import one of the prefab devices and throw it into a loss function. That code base lives in [google/`ceviche-challenges`](https://github.com/google/ceviche-challenges) and is also pip-installable as a package.

The only limitation of `ceviche_challenges` is that it uses HIPS autograd (like base Ceviche) and doesn't speak "JAX." The nice [`javiche`](https://github.com/Jan-David-Black/javiche/) package can be used to plug things into JAX. (See also https://github.com/Jan-David-Black/javiche/issues/1).

**Comment by lucasgrjn** [comment]
Hi!

If you take a look at [`notebook11`](https://github.com/flaport/inverse_design/blob/86486d609d447a5247e5b8fe97f6e24ebdd376e3/notebooks/11_ceviche_challenges.ipynb), it is indeed based on `ceviche-challenges` :)
Do you plan to publish any optimizers you use on the paper anytime ?

**Comment by ianwilliamson** [comment]
Whoops... missed that notebook (only got to `07_inverse_design.ipynb`).

We don't currently have plans to release any additional code from the paper. However, this repository seems to do a great job at filling the gap.

**Comment by lucasgrjn** [comment]
Thanks for the answer!

Some small details to fix and I think, the results will be reproduced!

**Comment by jan-david-fischbach** [comment]
> The only limitation of ceviche_challenges is that it uses HIPS autograd (like base Ceviche) and doesn't speak "JAX." The nice [javiche](https://github.com/Jan-David-Black/javiche/) package can be used to plug things into JAX. (See also https://github.com/Jan-David-Black/javiche/issues/1).

You have traced back the origin story of javiche ;)
