### ISSUE TITLE
What happened to `environment.yml`

### ISSUE THREAD

**Issue by jan-david-fischbach** [flaport/inverse_design#16]
Was it removed intentionally?

**Comment by flaport** [comment]
I might have accidentally deleted it. That said, maybe we don't need it as the dependencies are in the settings.cfg file anyway and are hence parsed by setup.py? 

In general I don't really like duplication of dependencies. But if you want it back feel free to make a PR :)

**Comment by jan-david-fischbach** [comment]
All good. The make arm_env stopped working. I'll replace it with something that relies on the package dependencies.
