### ISSUE TITLE
Migrate to nbdev v2?

### ISSUE THREAD

**Issue by jan-david-fischbach** [flaport/inverse_design#3]
Is there a particular reason not to migrate?
It seems like the github actions are currently failing because the nbdev command is not found.

**Comment by flaport** [comment]
The only reason I haven't done so, so far is because i know nbdev1 better. But converting a small repository like this would be the perfect opportunity to learn nbdev2. So yeah... Let's do it :)

**Comment by jan-david-fischbach** [comment]
I am currently preparing a pull request in my fork. I have migrated to nbdev version 2 according to the documentation. However, many things are still different to a project setup with nbdev_new (e.g. [javiche](https://github.com/Jan-David-Black/javiche))
I have my first "successful" optimization. I'll do some cleanup and provide additional documentation. 
<img width="400" alt="generated opt result" src="https://user-images.githubusercontent.com/92856893/216779106-2f6f2f0f-07cc-4178-80a2-bed7dda6efd8.png">
Somehow nbdev_prepare doesn't seem to cleanout the notebooks as expected. I'll do some more digging

**Comment by jan-david-fischbach** [comment]
To avoid problems with the pending PRs #5 and #6 I suggest that we run nbdev_migrate after they have been closed.

**Comment by flaport** [comment]
Hi Jan-David, I merged #4 in one go. I had to do it manually because the PR was coming from your master branch and I could not push to it. But you should be able to cleanly merge my master branch into yours now.
