### ISSUE TITLE
PATH modifications

### ISSUE THREAD

**Issue by jan-david-fischbach** [flaport/inverse_design#8]
We still have quite a lot of
```python
import sys; sys.path.insert(0, '..')
```
in the notebooks. With `maturin` in place now these should not be required anymore, as it installs the pyo3 bindings directly into the environment.

Suggestion:
get rid of the PATH manipulations :)

**Comment by flaport** [comment]
The path modifications were removed during the merge. Did you merge my master back into yours?

**Comment by jan-david-fischbach** [comment]
Jep I did. I was however still sitting on old files locally. Resolved
